project:
  type: website

website:
  title: "Hugo Gruson"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: https://orcid.org/0000-0002-4094-1476
      - text: "Blog"
        href: blog.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Software"
        href: software.qmd
      - text: "Presentations"
        href: slides.qmd
      - text: "Gallery"
        href: https://www.flickr.com/photos/138630183@N03/albums
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/bisaloo/bisaloo.github.io

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

