---
title: "Software"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html
library(magrittr)
```

# [R packages](https://cran.r-project.org/web/checks/check_results_hugo.gruson_r_at_normalesup.org.html)

```{r, results='asis'}
jsonlite::stream_in(url("https://bisaloo.r-universe.dev/stats/descriptions"), verbose = FALSE) %>%
  dplyr::arrange(Package) %>%
  split(rownames(.)) %>%
  purrr::map(unlist) %>%
  purrr::map_chr(function(e) {
    knitr::knit_expand(
      "_software-item.Rmd", 
      Package = e[["Package"]],
      Title = e[["Title"]],
      pkgdown_url = strsplit(e[["URL"]], ",")[[1]][1]
    )
  }) %>%
  { knitr::knit_child(text = unlist(.), quiet = TRUE) } %>%
  cat(sep = "\n")
```

# Other software

- [ULM (Unified Life Models)](https://www.biologie.ens.fr/~legendre/ulm/ulm.html) with Stéphane Legendre, François Bienvenu, Guilhem Doulcier, and Maxime Woringer: Software coded in free pascal, with a GTK or Qt graphical interface, enabling the simulation and analysis of deterministic and stochastic discrete time dynamical systems for population dynamics modeling.
