on:
  workflow_dispatch:
  schedule:
    - cron: '42 1 * * *'

jobs:
  fetch-deadlines:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      issues: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: gh

      - name: Fetch deadline for this package
        shell: Rscript {0}
        run: |
          crandb <- tools::CRAN_package_db()

          pkgname <- drop(read.dcf("DESCRIPTION", "Package"))

          deadline <- crandb[crandb$Package == pkgname, "Deadline"]

          if (!is.na(deadline)) {
            gh::gh(
              "POST /repos/{owner_repo}/issues",
              owner_repo = Sys.getenv("GITHUB_REPOSITORY"),
              title = paste("Fix CRAN R CMD check issues by", deadline),
              body = "This GHA workflow has been disabled. Please re-enable it when closing this issue."
            )
            gh::gh(
              "PUT /repos/{owner_repo}/actions/workflows/{workflow_id}/disable",
              owner_repo = Sys.getenv("GITHUB_REPOSITORY"),
              workflow_id = basename(Sys.getenv("GITHUB_WORKFLOW"))
            )
          }
