---
title: "FOSDEM 2024: From disconnected elements to a harmonious ecosystem"
author:
  - name: "Hugo Gruson"
    orcid: "0000-0002-4094-1476"
date: "2024-02-03"
categories: [interoperability, ecosystem, R, R packages]
---

These slides were prepared for a lightning talk at FOSDEM 2024, in the "Public Code and Digital Public Goods" devroom, organized by the [Foundation for Public Code](https://standard.publiccode.net/) and the [Digital Public Goods Alliance](https://digitalpublicgoods.net/).

```{=html}
<iframe width="780" height="500" src="FOSDEM 2024.pdf" title="Slides"></iframe>
```

## Transcript

Hi, my name is Hugo. I'm the lead software architect at data.org. Today, I'd like to discuss the work we're doing to build a harmonious ecosystem for epidemiology as part of the Epiverse-TRACE Project.

Scientific research increasingly relies on data science and computational tools across fields like epidemiology, climate science, and econometrics. However, maintaining and updating data pipelines has become complex. Changing a single step or using different software can require hours of data wrangling just to format inputs and outputs correctly. This maintenance is especially challenging during crises when rapid results are essential. When the next pandemic hits, we need to focus on actual science, not basic data wrangling.

Currently, we have some good isolated free software tools, but a robust ecosystem as a whole is what we truly need. This is precisely the goal of the Epiverse-TRACE project: to harmonize the epidemiology tooling ecosystem in R. We do this by making existing tools interoperable, supporting tools to adopt global standards (like those from the Digital Public Goods Alliance or organizations like rOpenSci), and fostering a sustainable community around these ideals.

Our goal isn't to erase established communities. We recognize the value of diverse solutions within a rich ecosystem. However, interoperability within this ecosystem is essential. To achieve this, we involve the community, working with both user groups such as public health institutes and NGOs and developer communities.

Our approach has already shown success. We've packaged and released many unmaintained, non-portable codebases and more tools than I can cover here. Notably, two of these tools are already registered Digital Public Goods, and one is in the process of submission.

Building a sustainable network of collaborators is exciting and ambitious, but it also comes with challenges. Research and academia are competitive spaces, which can make collaboration difficult. Additionally, communication in a multi-stakeholder network with numerous collaborators can lead to delays and miscommunication. Sustaining this effort is challenging, especially with uncertain funding in this space.

To conclude, responding effectively to the next crisis, whether it's the climate crisis or the next pandemic, will require interoperable tools built through collaborative, multi-stakeholder projects. While necessary, these complex communities bring challenges in communication, collaboration, and sustainability. Ultimately, what may appear to be a technical challenge often becomes a communication and social challenge as well.

With that, I'll end with a picture of our core project team. Please feel free to talk with me if you're interested in learning more. Thank you.
